name: deploy
on:
    workflow_run:
        workflows: ["prCheck"]
        types: 
            - completed
    pull_request:
        types:
            - closed
jobs:
    echo-if-merged:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        environment: Prod
        steps: 
            - name: Echo
              run: echo "Pull Request merged!"