name: deploy
on:
    workflow_run:
        workflows: ["prCheck"]
        types: 
            - completed
jobs:
    echo:
        runs-on: ubuntu-latest
        steps: 
            - name: Echo
              run: echo "Ceva"