name: Merge to Prod
on:
    workflow_run:
        workflows: ["Testing"]
        types: 
            - completed
    pull_request:
        types:
            - closed
jobs:
    echo-if-merged:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        environment: Prod
        steps: 
            - name: Pull Request merged!
              run: echo "Pull Request merged!"
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Checking all files are correct
              run: ls -la
            - name: Modify version file
              run: cat version.txt
