name: Testing
on: 
  pull_request:
jobs:
    validate:
      environment: Test
      env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: Build and Run Docker Compose for Test
            run: |
              docker-compose -f compose.yaml up -d --build
              echo "build"
              # Validate Nginx configuration
              docker-compose -f compose.yaml exec -ti test nginx -t -c /etc/nginx/nginx.conf
              echo "nginx verified"
              # Validate PHP syntax
              docker-compose -f compose.yaml exec -ti test php -l /nginx_php/index.php
              echo "php verified"
    deployment:
      needs: validate
      environment: Test
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ID_RSA: ${{ secrets.ID_RSA }}
        DEPLOY_VM: ${{ secrets.DEPLOY_VM }}
      runs-on: ubuntu-latest
      steps:
        - name: Create file artifact with key
          run: |
            echo "${{secrets.ID_RSA}}" > id_rsa
            chmod 600 id_rsa
        - name: Add VM to known hosts
          run: |
            sudo mkdir -p /.ssh
            ssh-keyscan -H ${{ secrets.DEPLOY_VM }} >> /.ssh/known_hosts
        - name: Connect to VM and run commands
          run: ssh -t -t -i id_rsa -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_VM }} << EOT
            echo "Connected to VM"
            pwd
            EOT
