name: PR Validation
on: pull_request
jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - name: Download Code
              uses: actions/checkout@v4
            - name: Build Docker image
              run: docker build -t test .
            - name: Validate Nginx configuration
              run: docker run --rm test nginx -t
            - name: Validate PHP syntax
              run: docker run --rm test php -l /usr/share/nginx/html/test.php