name: testing
on: push
jobs:
    test-docker-compose:
        runs-on: ubuntu-latest
        environment: Test
        steps:
            - name: Download Code
              uses: actions/checkout@v4
            # - name: Set secrets as environment variables
            #   run: echo "MYSQL_ROOT_PASSWORD=${{ secrets.TEST_DB_PASSWORD }}" >> $GITHUB_ENV;
            - name: Spin up the containers
              run: docker-compose up --build -d
              env:
                TEST_DB: ${{ secrets.TEST_DB }}
                TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
    # test-database:
    #     needs: test-docker-compose
    #     runs-on: ubuntu-latest
    #     environment: Test
    #     steps:
    #         - name: Test database
    #           run: 